---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "openstack-exporter.fullname" . }}
  labels:
{{- include "openstack-exporter.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{- include "openstack-exporter.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "openstack-exporter.labels" . | indent 8 }}
    spec:
      containers:
      - name: openstack-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --endpoint-type
        - {{ .Values.endpoint_type }}
        - {{ .Values.cloud }}
        {{- with .Values.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: openstack-config
            mountPath: /etc/openstack
        ports:
        - name: metrics
          containerPort: 9180
      volumes:
      - name: openstack-config
        secret:
          secretName: openstack-config
    {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
